### PR TITLE
Added merge sort program

### PR DESCRIPTION
**Pull request by urvashi-2004**

### CODE REVIEW

**Comment by urvashi-2004** [comment]
@chandug25 I have created a PR. Please check and update to get my contribution counted.

Thank you!

**Comment by urvashi-2004** [comment]
hii @chandug25 
Is this repository excluded from hacktoberfest23? Please find the screenshot below:

image


Please check and update to help me get my contribution counted. Thank you !!
Add the label "Hacktoberfest2023".

**Comment by urvashi-2004** [comment]
@chandug25 please solve this issue.

**Review by gschandrasekhar — COMMENTED** [review]
reviewed.

**Comment by chandug25** [comment]
please wait for atleast 3 hrs, and pleas update me after 3hrs. @urvashi-2004

**Comment by urvashi-2004** [comment]
@chandug25 still it is showing excluded

image

**Comment by gschandrasekhar** [comment]
We got some info regarding that, this repo is banned by hacktoberfest. so kindly please contribute to other repos i will merge pr after reviewing your code. @urvashi-2004

**Pull request merged**
